2E2I/mamomo-client

- src/components/TopAppBar.js
> 메인페이지 appBar 디자인

- src/components/DonationCard.js
- src/components/MainPageDonationList.js
> 메인페이지 기부 목록 디자인

- src/App.js
- src/pages/DesignTestPage/DesignTestPage.js
> 컴포넌트디자인테스트 페이지 생성

- src/components/SearchPageTagTitle.js
- src/components/SearchPageTags.js
- src/pages/SearchPage/SearchPage.js
추천, 인기, 모든 태그 디자인 (같은 디자인 공유해서 일단 SearchPageTagTitle.js, SearchPageTags.js 이렇게 하나씩으로만 작업해놓음)
> :sparkles: 태그 디자인 (#12 #13 #14)

- package.json
- src/App.js
- src/setupProxy.js
- yarn.lock
> 🐛 cors에러방지 설정 #36

- src/components/CardList.js
- src/components/DonationCard.js
- src/components/mainPageComponents/MainPageDonationList.js
- src/store/MainPageStore.js
설계 내용
- MainPageStore.js 생성
- 메인페이지 기부리스트 -> 기부리스트 -> 카드 순으로 설계
참고 사항
- 추천시스템에 따라서 수정할거임 일단 임시로 (캠페인 1,2,3,4) 넣었음
- 연습삼아 store(zustand) 사용하긴 했는데 추천시스템에 따라 쓸지 안쓸지 결정할게요 (지금은 안써도 될듯)
- 카드 줄 안맞는거 나중에 개선하겠음
- **섬네일 url안에 "(숫자)"문자 있으면 삭제해줘야 넘어와서 로직 처리함. ex(aaaa(1).jpg -> aaaa.jpg) 왜인지 모름**
**asios.get()로 불러온 오브젝트 "campaign" 안에 있는 배열 "campaigns"을 리액트가 제대로 인식 못함!! 
랜더링 조건 줄 때 Object.entries(campaign)로 오브젝트를 배열취급해서 넣어줘야하고 props도 배열로 넘겨줘야함
왜인지 모름...이래서 타입스크랩트 쓰나봄...내 6시간...**
> ✨ 메인페이지 기부리스트 설계

- src/components/RoundSearchBar.js
- src/pages/DesignTestPage/DesignTestPage.js
- src/pages/SearchPage/SearchPage.js
- 콘솔 워닝뜨는 코드 개선 (테스트 페이지, RoundSearchBar)
- 검색페이지 import 오류 수정 (단순 경로 수정)
- store, styles 폴더 src내로 이동 (src외부에 있으면 에러 뜸)
> 🎨 코드 및 구조 개선

- src/assets/fonts/fonts.css
- src/components/CardList.js
- src/components/DonationCard.js
- src/components/OldCardList.js
- src/components/OldDonationCard.js
- src/components/mainPageComponents/OldMainPageDonationList.js
- src/pages/DesignTestPage/DesignTestPage.js
- Noto Sans Korean 폰트 적용
- 이미지와 타이틀 사이 개선
- 금액 표시 개선
> 메인페이지 기부리스트 디자인 개선

- src/components/searchPageComponents/SearchPageTagTitle.js
- src/components/searchPageComponents/SearchPageTags.js
> :lipstick: 태그 디자인 수정 #51

- src/components/searchPageComponents/CategoryTagTitle.js
CategoryTagTitle.js 태그타이틀 수정(카테고리 태그 -> 모든 카테고리)
> 💄 태그타이틀 이름 수정 #62

- src/components/searchPageComponents/RecomendationTagTitle.js
- src/components/searchPageComponents/Top10Tag.js
- src/components/searchPageComponents/Top10TagTitle.js
- src/pages/SearchPage/SearchPage.js
> ✨ 인기태그 설계 #21

- src/App.js
- src/components/Categories.js
- src/pages/DesignTestPage/DesignTestPage.js
- src/pages/MainPage/MainPage2.js
/test2 로 가시면 메인페이지에 박혀있는 거 보실 수 있습니다.
> 카테고리 컴포넌트 디자인

- src/pages/SearchPage/SearchPage.js
> :lipstick: 검색페이지 태그 깨짐 수정 #71

- src/components/DonationListByCategorie.js
일단은 16개 항목만 나오도록 설계
더보기 방식 어떻게 할지 정하고 추가 설계 예정
> ✨ 카테고리페이지 기부리스트 설계 #74

- src/App.js
- src/components/DonationCard.js
- src/pages/CategoriePage/CategoriePage.js
> ✨ 카테고리 페이지 디자인 설계 #76

- package.json
- src/components/DonationListByCategorie.js
- yarn.lock
import { useInView } from 'react-intersection-observer'; 
따로 라이브러리 설치해서 사용
데이터는 한번에 받아오고
하단으로 내려올 때마다 20개씩 리스트 추가해서 보여주도록 설계
> ✨ 카테고리 기부 리스트 무한 스크롤 기능 구현 #78

- src/App.js
- src/components/searchPageComponents/CategoryTag.js
- src/components/tagPageComponents/TagPageDonationList.js
- src/components/tagPageComponents/TagTitle.js
- src/pages/TagPage/TagPage.js
- src/store/SearchPageStore.js
- 태그 페이지 일단 간단하게만 디자인했음
- 카테고리 태그 누르면 해당 카테고리 기부글 나옴(4개), 무한스크롤으로 수정 필요
- 근디 새로고침 누르면 안나옴. zustand 사용했는데 잘 모르겠네.. 버그 고칠게욥
> ✨ 태그 페이지 디자인, 카테고리 검색 설계 (#80, #66)

- package.json
- src/components/searchPageComponents/CategoryTag.js
- src/components/tagPageComponents/TagPageDonationList.js
- src/components/tagPageComponents/TagTitle.js
- src/pages/TagPage/TagPage.js
- src/store/CategoryPageStore.js
- src/store/SearchPageStore.js
- src/utils/persist.js
- yarn.lock
> 🐛 태그페이지 새로고침 버그 수정 #84

- package.json
- src/components/Categories.js
- src/components/DonationListByCategorie.js
- src/components/Paging.css
- src/components/Paging.js
- src/pages/CategoriePage/CategoriePage.js
- src/store/CategoryPageStore.js
- yarn.lock
기부 리스트 페이지 처리 완료
패키지 설치해서 했음
디자인 css로 처리 (불편...)
> 카테고리페이지 페이지네이션 처리

- src/App.js
- src/components/RoundSearchBar.js
- src/pages/SearchPage/SearchPage.js
- src/pages/SearchingPage/SearchingPage.js
- src/pages/SearchingPage/index.js
- src/store/SearchPageStore.js
- SearchPage의 SearchBar에서 검색 시 검색어 저장
- SearchBar에 검색한 검색어 뜨게 하는 거 고민 좀 해야댐
> ✨ SearchBar 설계 #19

- src/components/CardList.js
- src/components/CardList_old.js
- src/components/mainPageComponents/MainPageDonationList.js
- src/components/mainPageComponents/MainPageDonationList_old.js
- src/pages/MainPage/MainPage.js
> 🐛 메인페이지 기부리스트 버그 수정 #90

- src/components/DonationCard.js
- 공유하기. 배너 아이콘 삭제
- 좋아요 아이콘 우측에 숫자 표시
- 이미지 상단 우측에 사이트 타입 표시
> 💄 기부 목록 디자인 개선 #92

- src/App.js
- src/components/SearchingPageComponents/SearchingPageDonationList.js
- src/components/SearchingPageComponents/SearchingPageSearchBar.js
- src/pages/SearchPage/SearchPage.js
- src/pages/SearchingPage/SearchingPage.js
- 서치바에서 키워드 검색 기능 설계
-추가 수정/보완해야 할 사항
1. 서치바 유효성 검사 필요 (검색어 없어도 페이지 전환됨)
2. 1페이지만 보여짐 (페이지네이션 어렵네..)
3. 서치바 디자인 사용자 눈에 잘 띄도록 수정할 예정
> ✨ 검색어 기능 설계 #96

- src/components/signInPageComponents/ID.js
- src/components/signInPageComponents/MainTitle.js
- src/components/signInPageComponents/Password.js
- src/components/signInPageComponents/SignInButton.js
- src/pages/SignInPage/SignInPage.js
- 각 컴포넌트별 js 파일 생성
- 메인 타이틀, 아이디, 비밀번호, 로그인 버튼 임시 디자인
> ✨ 로그인페이지 컴포넌트 생성 #103

- src/components/signInPageComponents/Email.js
- src/components/signInPageComponents/FindingPassword.js
- src/components/signInPageComponents/KeepingSignIn.js
- src/components/signInPageComponents/KeepingSignInButton.js
- src/components/signInPageComponents/MainTitle.js
- src/components/signInPageComponents/Password.js
- src/components/signInPageComponents/SignIn.js
- src/components/signInPageComponents/SignInButton.js
- src/components/signInPageComponents/SignUp.js
- src/components/signInPageComponents/SplitedLine.js
- src/pages/SignInPage/SignInPage.js
- 회원가입 버튼(SignUp.js), 비밀번호 찾기 버튼(FindingPassword.js) 컴포넌트 디자인 
- 이메일 찾기(FindingEmail.js) 삭제 (아이디로 로그인이 아니라서)
> 💄 로그인페이지 컴포넌트 디자인 #110

- src/components/TopAppBar.js
- src/components/signInPageComponents/FindingPassword.js
- src/components/signInPageComponents/SignIn.js
- src/components/signInPageComponents/SignUp.js
- TopAppBar 마이페이지 버튼 -> 로그인 으로 변경
- FindingPassword.js, SignUp 컴포넌트 설명 주석 추가
> ✨ 로그인페이지 설계 #112

- src/App.js
- src/components/signInPageComponents/SignUp.js
- src/pages/SignUpPage/SignUpPage.js
- src/pages/SignUpPage/index.js
- 폴더 생성
- 페이지 생성
- 라우팅(로그인페이지에서 회원가입 버튼 누를 시)
> ✨ 회원가입페이지 세팅 #114

- src/components/signInPageComponents/Email.js
- src/components/signInPageComponents/FindingPassword.js
- src/components/signInPageComponents/KeepingSignIn.js
- src/components/signInPageComponents/Password.js
- src/components/signInPageComponents/SignIn.js
- src/components/signInPageComponents/SignUp.js
> 💄 로그인페이지 컴포넌트 디자인 수정 #121

- src/App.js
- src/components/TopAppBar.js
- src/pages/MainPage/MainPage.js
- src/pages/MakeBannerPage/MakeBannerPage.js
> 앱바 배너 페이지, 카테고리 페이지 링크 추가

- src/components/bannerPageComponents/BannerDesign.js
- src/components/bannerPageComponents/BannerPageTest.js
- src/components/bannerPageComponents/EditForm.js
- src/components/bannerPageComponents/Preview.js
- src/components/bannerPageComponents/SourceCode.js
- src/pages/MakeBannerPage/MakeBannerPage.js
궁금한 점
1. 편집기능 어디까지 해줄지...(현재는 제목하고 본문내용만)
2. 배너제작기능 권한 (비로그인도 가능??)
3. 배너제작페이지에서 기부글을 어떤 형식으로 가져오게 할지...(검색? 좋아요한 기부?)
> 💄 배너페이지 디자인 구현

- src/components/MainTitle.js
- src/components/signUpPageComponents/CheckingPassword.js
- src/components/signUpPageComponents/Email.js
- src/components/signUpPageComponents/Nickname.js
- src/components/signUpPageComponents/SignUp.js
- 이미 가입된 이메일 에러 문구? 어떻게 띄워줘야할 지 모르게씀..
> ✨ 회원가입페이지 설계 #120

- src/index.js
> ✨ 로그인 처리 issue/144

- src/App.js
- src/components/TopAppBar.js
- src/components/authenticationFunc.js
- src/components/signInPageComponents/SignIn.js
- src/store/SignInPageStore.js
- 닉네임이 대문자로 뿌려짐 왜지? 뭐지 %^..
- 레이아웃 안맞는건 눈 감아주십쇼..ㅠ
> ✨ 로그인 상태 TopAppBar 설계

- src/components/signUpPageComponents/Birth.js
> 🐛 회원가입 버그 수정 #156

- src/components/SplitedLine.js
- src/components/signInPageComponents/Email.js
- src/components/signInPageComponents/Password.js
- src/components/signUpPageComponents/CheckingPassword.js
- src/components/signUpPageComponents/Email.js
- src/components/signUpPageComponents/FavTopics.js
- src/components/signUpPageComponents/Nickname.js
- src/components/signUpPageComponents/Password.js
- src/components/signUpPageComponents/Sex.js
- src/components/signUpPageComponents/SignUp.js
- src/store/SignUpPageStore.js
Birth.js 는 이거 머지하고 추가하겠습니다 (충돌날 것 같애서)
> ✨ 회원가입 유효성 검사 추가 #155

- src/App.js
- src/components/DonationCard.js
- src/components/DonationListByCategory.js
- src/components/TopAppBar.js
- src/components/mainPageComponents/MainPageDonationList.js
- src/store/SignInPageStore.js
- 비로그인시 -> 알림뜨고 로그인페이지로 이동
- 로그인||이미 좋아요한 캠페인 -> 알림
문제점 (나중에 해결하겠움)
- 좋아요 누르고 바로 반영이 안됨 (새로고침 눌러야 반영)
- 좋아요 취소 기능 없음
> ✨ 좋아요 기능 구현 #160

- src/App.js
> ✨ 마이페이지 라우팅

- src/App.js
- src/components/SplitedLine.js
- src/components/TopAppBar.js
- src/components/myPageComponents/Title.js
- src/components/myPageComponents/UserTab.js
- src/components/myPageComponents/managingPageComponents/Birth.js
- src/components/myPageComponents/managingPageComponents/CancelButton.js
- src/components/myPageComponents/managingPageComponents/FavTopics.js
- src/components/myPageComponents/managingPageComponents/Nickname.js
- src/components/myPageComponents/managingPageComponents/ProfileImg.js
- src/components/myPageComponents/managingPageComponents/SaveButton.js
- src/components/myPageComponents/managingPageComponents/Sex.js
- src/pages/MyPage/LikePage.js
- src/pages/MyPage/ManagingPage.js
- src/pages/MyPage/MyBannerPage.js
- src/store/MyPageStore.js
[프로필 관리 페이지 설계 및 디자인]
- 프로필 이미지(ProfileImg.js)는 디자인만 해놈
- 회원가입 시에 관심 기부 분야 선택한 거 받아와서 체크했던거 표시해줘야하는데 안됨ㅜ.. 나중에 처리하게씀 
- 저장버튼은 api 구현되구 나서
> ✨💄 프로필 관리 설계 #168

- src/components/DonationCard.js
axios delete
- 헤더 먼저
- 바디 data로 감싸기
> 🐛 좋아요 취소 버그 수정 #181

- src/App.js
- 비로그인 상태로 배너제작으로 이동시 로그인 페이지로 보내버림
- 배너제작 페이지에서 로그아웃시 아주 잠깐 로그인페이지로 이동했다가 메인페이지로 이동함(약간 불편스)
> 🎨 배너제작 페이지 권한 부여 #185

- src/components/myPageComponents/managingPageComponents/Birth.js
- src/components/myPageComponents/managingPageComponents/CancelButton.js
- src/components/myPageComponents/managingPageComponents/FavTopics.js
- src/components/myPageComponents/managingPageComponents/Nickname.js
- src/components/myPageComponents/managingPageComponents/SaveButton.js
- src/components/myPageComponents/managingPageComponents/Sex.js
- src/store/ModifyProfileStore.js
- 관심 기부 분야 에러 나서 일단 주석 처리 해놈 (다른 프로필 데이터 수정 로직이랑 같음)
- 로그아웃 후 로그인 해야 수정한 내용 적용됨. whyrano..
> ✨ 프로필 수정 버튼 설계 #172

- src/components/TopAppBar.js
- src/components/myPageComponents/UserTab.js
- src/components/myPageComponents/managingPageComponents/ProfileImg.js
- src/components/myPageComponents/managingPageComponents/SaveButton.js
- src/components/signInPageComponents/SignIn.js
- src/store/ModifyProfileStore.js
- src/store/UserProfileStore.js
- 로그아웃하고 로그인해야 수정한 내용 적용되는 버그도 해결했음
> ✨ 프로필 이미지 수정 설계 #172

- src/components/DonationModal.js
'/~~~'로 이동 구현
import { useHistory } from 'react-router-dom/';
const history = useHistory();
history.push('/~~~');
이렇게 하시길 권장!
> 🐛 기부글에서 배너제작 이동시 경로변경 방법 변경 #195

- src/App.js
- src/components/TopAppBar.js
- src/components/textMiningPageComponents/SaveButton.js
- src/components/textMiningPageComponents/TextMiningField.js
- src/components/textMiningPageComponents/TextMiningPageBanner.js
- src/components/textMiningPageComponents/TextMiningPageDonationList.js
- src/pages/textMiningPage/TextMiningPage.js
- src/pages/textMiningPage/index.js
- src/store/TextMiningPageStore.js
- 텍스트 입력하면 바로 바로 기부글 뿌려주는 식으로 구현해놈.
- row수를 지정안해놓았고 입력한대로 높이 늘어남. (row 지정 가능은 함)
> ✨💄 텍스트마이닝 페이지 디자인 및 설계 #194

- src/components/myPageComponents/managingPageComponents/ProfileImg.js
- src/components/myPageComponents/managingPageComponents/SaveButton.js
- src/store/UserProfileStore.js
수정된 api에 맞춰 수정 (닉네임, 생년월일, 성별, 관심 기부 분야)
> ⚡️ 프로필 수정 버튼 설계 #172

- src/components/bannerPageComponents/Preview.js
미완성
일단은 서버저장 버튼을 누를 시에 서버에 저장
날짜는 임시로 박아둠
(나중에 다 처리할게욤,.,,)
> ✨ 배너 이미지 서버저장 코드 구현 #201

- src/components/textMiningPageComponents/SaveButton.js
- 빈 텍스트 필드이면 텍스트마이닝 버튼 disabled (못 누르게 함)
- 텍스트 있는 상태에서 텍스트마이닝 버튼 누르면 응답 올 때까지 circularProgress(로딩 바) 돌아감
- 응답 오면 로딩 바 없어지고 텍스트마이닝 버튼 나옴
> ✨ 텍스트마이닝페이지 로딩바 추가 #199

- src/components/searchPageComponents/AllTag.js
- src/components/searchPageComponents/AllTagTitle.js
- src/components/searchPageComponents/CategoryTag.js
- src/components/searchPageComponents/Top10Tag.js
- src/components/tagPageComponents/AllTagDonationList.js
- src/pages/SearchPage/SearchPage.js
- src/pages/TagPage/TagPage.js
- 더보기 누를 시 10개씩 더 보여줌
- 열고 닫을 수 있게 닫기, 열기 버튼 추가 했음
> ✨ 모든 태그 설계 #205

- src/components/BannerListPage/MasonryImageList.js
- src/components/bannerPageComponents/Preview.js
폼데이터: 현재시간 구현 및 배너 정보 추가
배너리스트 잘 나옵니다. 페이지 구현은 나중에..
> ✨ 배너 저장 폼데이터 수정 및 배너리스트 페이지 get메소드 구현 #211

- src/components/myPageComponents/managingPageComponents/Birth.js
- src/components/myPageComponents/managingPageComponents/SaveButton.js
- 생년월일 에러
- 프로필이미지 url 없을 경우 에러
> 🐛 프로필 관리 페이지 버그 수정 #219

- src/components/signInPageComponents/Email.js
- src/components/signInPageComponents/Password.js
- src/components/signInPageComponents/SignUp.js
- src/pages/SignInPage/SignInPage.js
> ⚡️ 로그인 엔터키 기능 추가 #221

- src/components/RoundSearchBar.js
- src/components/searchingPageComponents/SearchingPageDonationList.js
- src/components/searchingPageComponents/SearchingPageSearchBar.js
- src/components/tagPageComponents/AllTagDonationList.js
- src/components/tagPageComponents/CategoryTagDonationList.js
- src/pages/SearchPage/SearchPage.js
- src/pages/SearchingPage/SearchingPage.js
- src/pages/TagPage/TagPage.js
- src/store/SearchPageStore.js
- 서치바 버그 수정
- 검색된 기부글 개수 추가
- 검색 결과 없을 경우, "검색결과가 없습니다." 띄움
> ✨ 검색 설계 수정 #123

- src/components/textMiningPageComponents/SaveButton.js
> 💄 텍스트마이닝페이지 기부글 정렬 수정 #230

- src/components/bannerPageComponents/Preview.js
- src/components/myPageComponents/myBannerPageComponents/MyBannerList.js
IO에러 때문에 일단 마이배너는 5개만 가져오도록 했음.. 나중에 페이징처리할게요,,
> 🎨 배너 편집 기능 수정 #237

- README.md
> 📝 README 작성 #253

- src/components/signUpPageComponents/SignUp.js
> ⚡️ 회원가입 성공 라우팅 추가 #256
